### PR TITLE
Fix mapping name

### LINKED ISSUE #60: Don't print `main_` in specie names
It's just redundant, as it will end up being applied to all specie names. We could add a check akin to `if moduleName != main then addPrefix`. 

Fixing the tests should just be a matter of `:%s/main_//g`

### LINKED ISSUE #64: Mapping of species name move
As per [this comment](https://github.com/RasmusRendal/chemilang/pull/63/files#r417839605)

### LINKED ISSUE #66: Big Bug reactions with COEFFICIENT is not getting compiled to CRN
Reactions of the form: x + y -> 2y;  are not being compiled.

### PR DESCRIPTION
**Pull request by Andrikz**
Don't know if this is okay or it can be made in a better way

### CODE REVIEW

File: src/module.cpp [hunk 1]
```diff
@@ -128,3 +137,23 @@ void Module::VerifyFunction() {
 		}
 	}
 }
+std::string Module::MapName(std::string moduleName, std::string specieName,
```
Comment (RasmusRendal) [inline src/module.cpp]: The module should already know what it's own name is, so there is no need to supply it as an argument

File: src/module.h [hunk 2]
```diff
@@ -57,6 +57,9 @@ class Module {
 	Module() {}
 	void Verify();
 	void VerifyFunction();
+	std::string MapName(std::string moduleName, std::string specieName,
```
Comment (RasmusRendal) [inline src/module.h]: What is specieNumber? Is it the composition number?

File: src/module.cpp [hunk 3]
```diff
@@ -128,3 +137,23 @@ void Module::VerifyFunction() {
...
+														int specieNumber) {
+	std::string output;
+	if (moduleName != "main") {
```
Comment (RasmusRendal) [inline src/module.cpp]: `"main"` is a bit of a magic number, and should probably be defined as a const.

File: src/module.cpp [hunk 4]
```diff
@@ -61,7 +66,11 @@ std::string Module::Compile() {
 		const auto &products = reaction.products;
 		if (!products.empty()) {
 			for (const auto &specie : reaction.products) {
-				output += name + "_" + specie.first + " + ";
+				if (name != "main") {
```
Comment (RasmusRendal) [inline src/module.cpp]: Shouldn't you just use the MapSpecie function here, and the other places?

**Review by RasmusRendal — CHANGES_REQUESTED** [review]

**Comment by RasmusRendal** [comment]
Maybe you could split the MapSpecie function up into two functions, MapCompositionSpecie, and MapSpecie. That might make the code clearer.

File: src/module.cpp [hunk 5]
```diff
@@ -25,24 +27,23 @@ std::string Module::Compile() {
 	if (outputSpecies.size() > 0) {
 		output += "-C ";
 		for (const auto &specie : outputSpecies) {
-			output += name + "_" + specie + ",";
+			if (name != "main") {
```
Comment (RasmusRendal) [inline src/module.cpp]: Her er noget mapping udenfor mapSpecies funktionen

File: src/module.cpp [hunk 6]
```diff
@@ -128,3 +129,33 @@ void Module::VerifyFunction() {
 		}
 	}
 }
+
+const std::string Module::MapSpecie(const std::pair<std::string, int> &specie) {
```
Comment (RasmusRendal) [inline src/module.cpp]: This function should probably be split up into two. As I see it, it maps the specie name with the module name, and adds the concentration number to the string.

And if you find yourself describing a function using the word "and", that means you should have two functions. 

An added benefit of splitting it up would be that you don't have to do the `if (specie.second != 1)` logic twice.

File: src/module.cpp [hunk 7]
```diff
@@ -128,3 +129,33 @@ void Module::VerifyFunction() {
...
+			output += std::to_string(specie.second) + specie.first + " + ";
+		} else {
+			output += specie.first + " + ";
+		}
+	}
+	return output;
+}
+const std::string Module::MapConcs(const std::pair<std::string, int> &concs) {
+	std::string output;
+	if (name != mainModuleName) {
```
Comment (RasmusRendal) [inline src/module.cpp]: Again a case of why you should split up the previous function. If you had a function, which only had the function of mapping a specie name, you could have used it here, instead of repeating the `if name != mainModuleName)` logic.

**Review by RasmusRendal — CHANGES_REQUESTED** [review]

File: src/module.cpp [hunk 8]
```diff
@@ -128,3 +130,22 @@ void Module::VerifyFunction() {
 		}
 	}
 }
+
+std::string Module::MapSpecieReact(const std::pair<std::string, int> &specie) {
```
Comment (RasmusRendal) [inline src/module.cpp]: Many of these functions don't actually map, but are closer to something like "SpecieToString".

File: src/module.cpp [hunk 9]
```diff
@@ -128,3 +130,22 @@ void Module::VerifyFunction() {
...
+	return MapSpecieCoef(specie.second) + MapSpecie(specie.first) + " + ";
+}
+
+std::string Module::MapSpecieCoef(int coeff) {
+	return (coeff != 1) ? std::to_string(coeff) : "";
+}
+
+std::string Module::MapSpecie(const std::string &specie) {
+	return (name == constants::MAIN_MODULE) ? specie : name + "_" + specie;
```
Comment (RasmusRendal) [inline src/module.cpp]: So I just realised something. `Compile()`is only ever really called on the main module. So this function might actually be completely unnecessary.

**Review by RasmusRendal — CHANGES_REQUESTED** [review]

**Review by RasmusRendal — APPROVED** [review]
